spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:casino.db
    username: sa
    password: sa
    hikari:
      connection-timeout: 3000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
