###

DELETE {{host}}/api/transfers/5a66af69-0fd7-4416-8ccc-220c673fc6b3
Content-Type: application/json

###

PUT {{host}}/api/players
Content-Type: application/json

{
  "username": "alpha",
  "firstName": "Alpha",
  "lastName": "Beta",
  "balance": 1000.0
}

###

PUT {{host}}/api/players
Content-Type: application/json

{
  "username": "gamma",
  "firstName": "Gamma",
  "lastName": "Delta",
  "balance": 1000.0
}

###

PUT {{host}}/api/players
Content-Type: application/json

{
  "username": "epsilon",
  "firstName": "Epsilon",
  "lastName": "Zeta",
  "balance": 1000.0
}

###

PUT {{host}}/api/players
Content-Type: application/json

{
  "username": "eta",
  "firstName": "Eta",
  "lastName": "Theta",
  "balance": 1000.0
}

###

PUT {{host}}/api/players
Content-Type: application/json

{
  "username": "iota",
  "firstName": "Iota",
  "lastName": "Kappa",
  "balance": 1000.0
}